name: ej1-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Ejecutar comandos
      run: |
        npm i
        npm test
        
    - name: Acción final
      uses: cloudposse/github-action-docker-compose-test-run@main
      with:
            file: docker-compose.yml
